### ISSUE TITLE
Country code XX still ?

### ISSUE THREAD

**Issue by centminmod** [Xon/XenForo_TPUDetectSpamReg#1]
@Xon  using your version of and seems I am started getting XX for country code issue outlined at https://github.com/W1zzardTPU/XenForo_TPUDetectSpamReg/issues/3 after I moved a Xenforo forum to a new server ?

Could this happen if php geoip extension is missing ?

I have the default 2 checked options from

* Use Team Cymru DSN API for ASN lookup `checked`
* Use moocher.io HTTP API for ASN lookup `checked`
* Use RIPE HTTP API for ASN lookup

ip `107.77.196.51` at registrtaion time reports XX

```
ip=107.77.196.51
```

```
curl -s http://ip-api.com/json/$ip | jq                   
{
  "as": "AS20057 AT&T Mobility LLC",
  "city": "El Dorado",
  "country": "United States",
  "countryCode": "US",
  "isp": "AT&T Wireless",
  "lat": 33.2076,
  "lon": -92.6663,
  "org": "AT&T Wireless",
  "query": "107.77.196.51",
  "region": "AR",
  "regionName": "Arkansas",
  "status": "success",
  "timezone": "America/Chicago",
  "zip": ""
}
```

```
curl -s https://freegeoip.net/json/$ip | jq
{
  "ip": "107.77.196.51",
  "country_code": "US",
  "country_name": "United States",
  "region_code": "TX",
  "region_name": "Texas",
  "city": "",
  "zip_code": "",
  "time_zone": "America/Chicago",
  "latitude": 32.7787,
  "longitude": -96.8218,
  "metro_code": 0
}
```

maybe add a 3rd provider https://xenforo.com/community/threads/tpu-detect-and-block-spam-registrations.70418/page-12#post-1056400

```
curl http://ipinfo.io/8.8.8.8
{
  "ip": "8.8.8.8",
  "hostname": "google-public-dns-a.google.com",
  "city": "Mountain View",
  "region": "California",
  "country": "US",
  "loc": "37.3845,-122.0881",
  "org": "AS15169 Google Inc.",
  "postal": "94040"
}
```

**Comment by Xon** [comment]
Are there are any error logs around this time related to network connectivity?

**Comment by centminmod** [comment]
ah seems problem was geoip pecl extension wasn't loaded. It seems to register country codes now heh

**Comment by Xon** [comment]
@centminmod I recommend using this branch; https://github.com/Xon/XenForo_TPUDetectSpamReg/tree/multi-records It has a revised country resolution code

**Comment by centminmod** [comment]
sweet thanks for the heads up !
